# Global build settings
[build]
  # Install dependencies and build the entire project
  command = "npm install && npm run build"
  publish = "ui/dist"
  functions = "netlify/functions/dist"
  
  # Environment variables for build process
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--prefix=netlify/functions"
  
  # Function configuration
  [functions]
    node_bundler = "esbuild"
    external_node_modules = ["@commercelayer/sdk"]
    directory = "netlify/functions/dist"
    node_module_format = "esm"
    sourcemap = true
    node_version = "18"

# Proxy API requests to Netlify Functions - must come before the catch-all
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Explicit redirects for functions
[[redirects]]
  from = "/.netlify/functions/featured-products"
  to = "/.netlify/functions/featured-products"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/commerce-layer-auth"
  to = "/.netlify/functions/commerce-layer-auth"
  status = 200
  force = true

# CORS configuration for API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# This rule ensures that any direct navigation to a frontend route (e.g., /products-page)
# is handled by your React app's router (by serving index.html).
# This is essential for Single Page Applications (SPAs).
# The '!' prefix makes this a negative lookahead to exclude /api/* paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 # A 200 status indicates a rewrite (serve this file) not a 301/302 redirect.

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self';
      connect-src 'self' *.commercelayer.io *.commercelayer.co *.commercelayer.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
      object-src 'none';
    """

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables configuration
[context.production.environment]
  # Commerce Layer Configuration
  COMMERCE_LAYER_CLIENT_ID = "${COMMERCE_LAYER_CLIENT_ID}"
  COMMERCE_LAYER_CLIENT_SECRET = "${COMMERCE_LAYER_CLIENT_SECRET}"
  COMMERCE_LAYER_ORGANIZATION = "${COMMERCE_LAYER_ORGANIZATION}"
  COMMERCE_LAYER_DOMAIN = "${COMMERCE_LAYER_DOMAIN}"
  COMMERCE_LAYER_EU_SCOPE = "${COMMERCE_LAYER_EU_SCOPE}"
  COMMERCE_LAYER_UK_SCOPE = "${COMMERCE_LAYER_UK_SCOPE}"
  COMMERCE_LAYER_EU_SKU_LIST_ID = "${COMMERCE_LAYER_EU_SKU_LIST_ID}"
  COMMERCE_LAYER_UK_SKU_LIST_ID = "${COMMERCE_LAYER_UK_SKU_LIST_ID}"
  
  # App Configuration
  NODE_ENV = "production"
  APP_TITLE = "Seth's Triathlon Haus"
  APP_ID = "seths-triathlon-haus"
  
  # API Configuration
  API_URL = "https://seth-haus.netlify.app/.netlify/functions"
  WS_API_URL = "wss://seth-haus.netlify.app"

[context.development]
  command = "npm run dev"
  [context.development.environment]
    # Development Environment
    NODE_ENV = "development"
    NETLIFY_DEV_URL = "http://localhost:9999"
    
    # Commerce Layer Configuration - Development
    COMMERCE_LAYER_DOMAIN = "commercelayer.io"
  COMMERCE_LAYER_CLIENT_ID = "3uRXduKWJ8qr4G7lUBdrC1GFormL5Qa-RbFy-eCIGtA"
  COMMERCE_LAYER_CLIENT_SECRET = "REMOVED"
  COMMERCE_LAYER_ORGANIZATION = "seth-s-triathlon-haus"
  COMMERCE_LAYER_DOMAIN = "commercelayer.io"  # Just the domain, not the full URL
  COMMERCE_LAYER_EU_SCOPE = "market:qjANwhQrJg"
  COMMERCE_LAYER_UK_SCOPE = "market:vjzmJhvEDo"
  COMMERCE_LAYER_EU_SKU_LIST_ID = "JjEpIvwjey"
  COMMERCE_LAYER_UK_SKU_LIST_ID = "nVvZIAKxGn"