[build]
  command = "npm run build"
  publish = "ui/dist"
  functions = "netlify/functions/dist"

[dev]
  command = "cd ui && npm run dev"
  port = 8888
  targetPort = 5173
  framework = "vite"
  publish = "ui"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@commercelayer/sdk"]
  included_files = ["netlify/functions/src/*.ts", "!**/*.d.ts"]

[dev.environment]
  NODE_ENV = "development"
  NETLIFY_DEV = "true"
  API_URL = "http://localhost:9999"
  COMMERCE_LAYER_AUTH_URL = "https://auth.commercelayer.io/oauth/token"
  COMMERCE_LAYER_API_URL = "https://seth-s-triathlon-haus.commercelayer.io"
  PUBLIC_URL = "http://localhost:8888"

[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    PUBLIC_URL = "https://seth-haus.netlify.app"
    API_URL = "https://seth-haus.netlify.app/.netlify/functions"
    COMMERCE_LAYER_AUTH_URL = "https://auth.commercelayer.io/oauth/token"
    COMMERCE_LAYER_API_URL = "https://seth-s-triathlon-haus.commercelayer.io"
    COMMERCE_LAYER_CLIENT_ID = "${COMMERCE_LAYER_CLIENT_ID}"
    COMMERCE_LAYER_CLIENT_SECRET = "${COMMERCE_LAYER_CLIENT_SECRET}"
    COMMERCE_LAYER_ORGANIZATION = "${COMMERCE_LAYER_ORGANIZATION}"
    COMMERCE_LAYER_DOMAIN = "${COMMERCE_LAYER_DOMAIN}"
    COMMERCE_LAYER_EU_SCOPE = "${COMMERCE_LAYER_EU_SCOPE}"
    COMMERCE_LAYER_UK_SCOPE = "${COMMERCE_LAYER_UK_SCOPE}"
    COMMERCE_LAYER_EU_SKU_LIST_ID = "${COMMERCE_LAYER_EU_SKU_LIST_ID}"
    COMMERCE_LAYER_UK_SKU_LIST_ID = "${COMMERCE_LAYER_UK_SKU_LIST_ID}"
