[build]
command = "cd ui && npm install && npm run build && cd ../netlify/functions && npm install && npm run build"
publish = "ui/dist"
functions = "netlify/functions/dist"

[dev]
framework = "#custom"
command = "npm run dev:ui"
targetPort = 5173
publish = "ui"
port = 8888
functions = "netlify/functions/dist"

[dev.environment]
NODE_ENV = "development"
COMMERCE_LAYER_CLIENT_ID = "${COMMERCE_LAYER_CLIENT_ID}"
COMMERCE_LAYER_CLIENT_SECRET = "${COMMERCE_LAYER_CLIENT_SECRET}"
COMMERCE_LAYER_ORGANIZATION = "${COMMERCE_LAYER_ORGANIZATION}"
COMMERCE_LAYER_DOMAIN = "${COMMERCE_LAYER_DOMAIN}"
COMMERCE_LAYER_EU_SCOPE = "${COMMERCE_LAYER_EU_SCOPE}"
COMMERCE_LAYER_UK_SCOPE = "${COMMERCE_LAYER_UK_SCOPE}"
COMMERCE_LAYER_EU_SKU_LIST_ID = "${COMMERCE_LAYER_EU_SKU_LIST_ID}"
COMMERCE_LAYER_UK_SKU_LIST_ID = "${COMMERCE_LAYER_UK_SKU_LIST_ID}"
APP_TITLE = "${APP_TITLE}"
API_URL = "/.netlify/functions"

[functions]
directory = "netlify/functions/dist"
node_bundler = "esbuild"
included_files = ["netlify/functions/src/**", "!**/*.d.ts"]

[context.production]
command = "cd ui && npm install && npm run build && cd ../netlify/functions && npm install && npm run build"
publish = "ui/dist"
functions = "netlify/functions/dist"

[context.production.environment]
NODE_ENV = "production"
COMMERCE_LAYER_CLIENT_ID = "${COMMERCE_LAYER_CLIENT_ID}"
COMMERCE_LAYER_CLIENT_SECRET = "${COMMERCE_LAYER_CLIENT_SECRET}"
COMMERCE_LAYER_ORGANIZATION = "${COMMERCE_LAYER_ORGANIZATION}"
COMMERCE_LAYER_DOMAIN = "${COMMERCE_LAYER_DOMAIN}"
COMMERCE_LAYER_EU_SCOPE = "${COMMERCE_LAYER_EU_SCOPE}"
COMMERCE_LAYER_UK_SCOPE = "${COMMERCE_LAYER_UK_SCOPE}"
COMMERCE_LAYER_EU_SKU_LIST_ID = "${COMMERCE_LAYER_EU_SKU_LIST_ID}"
COMMERCE_LAYER_UK_SKU_LIST_ID = "${COMMERCE_LAYER_UK_SKU_LIST_ID}"
APP_TITLE = "${APP_TITLE}"
API_URL = "https://seth-haus.netlify.app/.netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "http://localhost:5173"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Credentials = "true"
Vary = "Origin, Access-Control-Request-Headers, Access-Control-Request-Method"
