[build]
command = "npm install && cd ui && npm install && npm run build && cd ../netlify/functions && npx tsc"
publish = "ui/dist"
functions = "netlify/functions/dist"

[dev]
framework = "#custom"
command = "npm run dev:ui"
targetPort = 5173
publish = "ui"
port = 8888
functions = "netlify/functions/dist"

[functions]
directory = "netlify/functions/dist"
node_bundler = "esbuild"
included_files = ["netlify/functions/src/**", "!**/*.d.ts"]

[context.production]
command = "npm install && cd ui && npm install && npm run build && cd ../netlify/functions && npx tsc"
publish = "ui/dist"
functions = "netlify/functions/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "http://localhost:5173"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Credentials = "true"
Vary = "Origin, Access-Control-Request-Headers, Access-Control-Request-Method"
