
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const FAQPage = lazy(() => import("./pages/FAQPage.tsx"));
const ProductDetailPage = lazy(() => import("./pages/ProductDetailPage.tsx"));
const Products = lazy(() => import("./pages/Products.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/faq-page", element: <FAQPage />},
	{ path: "/faqpage", element: <FAQPage />},
	{ path: "/product-detail-page", element: <ProductDetailPage />},
	{ path: "/productdetailpage", element: <ProductDetailPage />},
	{ path: "/products", element: <Products />},

];
