
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router";

import App from "pages/App";
import FAQPage from "pages/FAQPage";
import ProductDetailPage from "pages/ProductDetailPage";
import Products from "pages/Products";
import HomePage from "pages/HomePage";

export const userRoutes: RouteObject[] = [
  {
    path: "/",
    element: <App />,
    children: [
      { index: true, element: <HomePage /> },
      { path: "products", element: <Products /> },
      { path: "faq-page", element: <FAQPage /> },
      { path: "faqpage", element: <FAQPage /> },
      { path: "product-detail-page", element: <ProductDetailPage /> },
      { path: "productdetailpage", element: <ProductDetailPage /> },
    ]
  }
];
