import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useNavigate } from "react-router-dom";
import { MarketSwitcher } from "./MarketSwitcher";
import { useAppContext } from "./AppProvider";
export default function SimpleHeader({ selectedMarket, onMarketChange }) {
    const navigate = useNavigate();
    const { clReady } = useAppContext();
    return (_jsx("header", { className: "sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60", children: _jsxs("div", { className: "container flex h-16 items-center justify-between px-4 md:px-6", children: [_jsx("div", { className: "flex items-center", children: _jsx(Link, { to: "/", className: "flex items-center space-x-2", children: _jsx("span", { className: "font-bold text-2xl", children: "Seth's Triathlon Haus" }) }) }), _jsxs("nav", { className: "hidden md:flex flex-1 items-center justify-center space-x-6", children: [_jsx(Link, { to: "/products?category=swim", className: "text-base font-medium text-muted-foreground transition-colors hover:text-foreground", children: "Swim" }), _jsx(Link, { to: "/products?category=bike", className: "text-base font-medium text-muted-foreground transition-colors hover:text-foreground", children: "Bike" }), _jsx(Link, { to: "/products?category=run", className: "text-base font-medium text-muted-foreground transition-colors hover:text-foreground", children: "Run" }), _jsx(Link, { to: "/products?category=triathlon", className: "text-base font-medium text-muted-foreground transition-colors hover:text-foreground", children: "Triathlon" })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(MarketSwitcher, { selectedMarket: selectedMarket, onMarketChange: onMarketChange }), clReady && (_jsxs("div", { className: "relative ml-4 flex items-center", children: [_jsxs("svg", { width: "24", height: "24", viewBox: "0 0 32 32", fill: "none", xmlns: "http://www.w3.org/2000/svg", className: "h-6 w-6", children: [_jsx("path", { d: "M27 6H5C4.44772 6 4 6.44772 4 7V25C4 25.5523 4.44772 26 5 26H27C27.5523 26 28 25.5523 28 25V7C28 6.44772 27.5523 6 27 6Z", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M4 10H28", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M21 14C21 15.3261 20.4732 16.5979 19.5355 17.5355C18.5979 18.4732 17.3261 19 16 19C14.6739 19 13.4021 18.4732 12.4645 17.5355C11.5268 16.5979 11 15.3261 11 14", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" })] }), _jsx("cl-cart", {})] }))] })] }) }));
}
